Deploy/tapapp/tapapp/urls.py
from django.conf.urls import url
from django.contrib import admin


import tapesbars.views as tv


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', tv.BarListView.as_view(), name='Bars'),
    url(r'^bars/(?P<pk>[0-9]+)$', tv.BarDetailView.as_view(), name='Bars_Detail'),
]

Deploy/tapapp/tapesbars/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import reverse
from django.db import models

# Create your models here.

class Bar(models.Model):
    name = models.CharField(max_length=80)
    addr = models.TextField(max_length=100)

    def __unicode__(self):
        return self.name+" "+self.addr

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this book.
        """
        return reverse('Bars_Detail', args=[str(self.id)])


class Tapes(models.Model):
    """Tapes"""
    name = models.CharField(max_length=80)
    price = models.IntegerField()
    bar = models.ForeignKey(Bar)

    def __unicode__(self):
        return self.bar.name+"-"+self.name

Deploy/tapapp/tapesbars/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic

from .models import Bar, Tapes

# Create your views here.

class BarListView(generic.ListView):
    model = Bar

class BarDetailView(generic.DetailView):
    model = Bar

Deploy/tapapp/templates/tapesbars/bar_detail.html
{% block content %}
  <h1>Bar: {{ bar.name }}</h1>

  <p><strong>Addr:</strong>{{ bar.addr}}</p>

  <div style="margin-left:20px;margin-top:20px">
      <h4>Tapes</h4>
      <ul>
      {% for tapa in bar.tapes_set.all %}
      <li><p><strong>Tapa:</strong> {{tapa.name}}</p>
      </li>
      {% endfor %}
      </ul>
  </div>
{% endblock %}

Deploy/tapapp/templates/tapesbars/bar_list.html
{% block content %}
    <h1>Bars</h1>

    {% if bar_list %}
    <ul>

      {% for bar in bar_list %}
      <li>
        <a href="{{ bar.get_absolute_url }}">{{ bar.name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No bars available.</p>
    {% endif %}
{% endblock %}